assigness: []
harvest_options:
  goldcopy: false
  path: s3://ooi-data
  refresh: true
  test: false
instrument: RS03AXPS-SF03A-4B-VELPTD302
stream:
  method: streamed
  name: velpt_user_configuration
workflow_config:
  schedule: 0 0 * * *
